theme = "boksfisika"
summaryLength = 2 

title = "307"
# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
# Shortname disqus, silahkan sesuaikan
DisqusShortname = "Boks Fisika"

# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "G-BM7MNLDFB6" 

# Untuk deskripsi tag meta di homepage
description = "Blog Seputar Fisika"
baseURL = "https://asharimidana.github.io/"

paginate = 2

# Biodata Author
[author]
    [author.ari]
        name = "Ashari Midana"
        homepage = ""
        image = "/profil.jpg" 

